apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-mini-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubernetes-mini-app
  template:
    metadata:
      labels:
        app: kubernetes-mini-app
    spec:
      containers:
        - name: kubernetes-mini-app-container
          image: upendra787/kubernetes-demo-app:latest
          ports:
            - containerPort: 8082
